### ISSUE TITLE
How Print the label of test sample?

### ISSUE THREAD

**Issue by alighofrani95** [ptirupat/AnomalyDetection_CVPR18#1]
thanks a lot for sharing project,
prediction.shape returns [32,1] I can't understand It's meaning.

the ucf-crime dataset has 14class (13 abnormal + 1 normal) how it became to 32???
and finaly how can i find the estimated label of test video?

**Comment by ptirupat** [comment]
The features from all 16 frame segments of the video are extrapolated into 32 feature bags and the output (prediction) is of shape [32,1] as it is the binary predictions for these 32 bags. Please refer to the paper. These predictions are then extrapolated for the whole video to get per-frame anomaly score.
