### ISSUE TITLE
C3d_model_weight file missing + ValueError: You are trying to load a weight file containing 0 layers into a model with 11 layers.

### ISSUE THREAD

**Issue by k173038** [ptirupat/AnomalyDetection_CVPR18#4]
in C3d.py File:
    if weights == 'sports1M':
        model.load_weights(cfg.c3d_model_weights)
    return model

in configurations.py file:
c3d_model_weights = './trained_models/c3d_sports1m.h5'

but no such weights are attached in above mentioned directory. In addition to that, I have downloaded the weights from drop box  and got below error:

ValueError: You are trying to load a weight file containing 0 layers into a model with 11 layers.

Kindly assist to resolve this.

**Comment by ptirupat** [comment]
Read the README file carefully. I have given the link from where you could download the weights. Best of luck !!
