### ISSUE TITLE
IndexError: tuple index out of range

### ISSUE THREAD

**Issue by ghost** [ptirupat/AnomalyDetection_CVPR18#5]
Sir, great job in re-implementation of the project. while trying to run the demo.py with another video (from same dataset), I am getting the following error. can you please help me with this issue

Traceback (most recent call last):
  File "demo.py", line 53, in <module>
    run_demo()
  File "demo.py", line 38, in run_demo
    rgb_feature_bag = interpolate(rgb_features, params.features_per_bag)
  File "/home/workspace/AnomalyDetection_CVPR18-master/utils/array_util.py", line 19, in interpolate
    feature_size = np.array(features).shape[1]
IndexError: tuple index out of range

Thank you for your time.
p.s: could you please provide a contact information for further clarifications

**Comment by ptirupat** [comment]
Hello, can you check the length of the array _rgb_features_ ? I suspect it is empty and hence you get this error. You could also check how many video_clips you get from your input video.

**Comment by k173038** [comment]
> Sir, great job in re-implementation of the project. while trying to run the demo.py with another video (from same dataset), I am getting the following error. can you please help me with this issue
> 
> Traceback (most recent call last):
> File "demo.py", line 53, in
> run_demo()
> File "demo.py", line 38, in run_demo
> rgb_feature_bag = interpolate(rgb_features, params.features_per_bag)
> File "/home/workspace/AnomalyDetection_CVPR18-master/utils/array_util.py", line 19, in interpolate
> feature_size = np.array(features).shape[1]
> IndexError: tuple index out of range
> 
> Thank you for your time.
> p.s: could you please provide a contact information for further clarifications

Dear Harsha,

I have faced the exactly same issue, that was because of the sample video file that was not in read-able format. Kindly check whether you can execute that video outside this testing environment.

**Comment by ghost** [comment]
Sir,
As you said, the reason for the video not being loaded is because of the sample video path in the "configuration.py" . Also while generating the report, the writer being used is Imagemagick and by default (in most systems) "ffmpeg" is used instead and following error could pop up

"ValueError: Invalid file object: <_io.BufferedReader name=6>"

**Solution**: (For anaconda users) install imagemagick using conda install
conda install -c kalefranz imagemagick

**Comment by Shiny128** [comment]
Hello @y-harsha ,@k173038
Have you figured out how to resolve the error?
I am still getting the following error when I run demo.py using a different video from the same dataset.

 Using Theano backend.
Number of clips in the video :  0
Models initialized
Traceback (most recent call last):
  File "demo.py", line 53, in <module>
    run_demo()
  File "demo.py", line 38, in run_demo
    rgb_feature_bag = interpolate(rgb_features, params.features_per_bag)
  File "/home/dell/Documents/AnomalyDetection_CVPR18-master/utils/array_util.py", line 19, in interpolate
    feature_size = np.array(features).shape[1]
IndexError: tuple index out of range

Please help me fix it 

Thank you

**Comment by ghost** [comment]
Yes, It is because of the sample video path in the configuration file. you have to change the video path in the 'configuration.py'. Replace "Explosion.mp4" with the name of the video you chose to copy to the input folder and then run the demo.py

**Comment by cervantes-loves-ai** [comment]
**still have same error. *installed imagemagick, checked video path,trying with example video, all those Libraries installed which is mentioned.** 

Using Theano backend.
Number of clips in the video :  0
Models initialized
Traceback (most recent call last):
  File "demo.py", line 53, in <module>
    run_demo()
  File "demo.py", line 38, in run_demo
    rgb_feature_bag = interpolate(rgb_features, params.features_per_bag)
  File "/media/AnomalyDetection_CVPR18-latest/utils/array_util.py", line 19, in interpolate
    feature_size = np.array(features).shape[1]
IndexError: tuple index out of range

**Comment by esraa-alaa** [comment]
Hello @y-harsha ,@k173038
Have you figured out how to resolve the error?
I am still getting the following error when I run demo.py using a different video from the same dataset.
File "E:\Codes\AnomalyDetection_CVPR18-master\demo.py", line 54, in <module>
    run_demo()

  File "E:\Codes\AnomalyDetection_CVPR18-master\demo.py", line 39, in run_demo
    rgb_feature_bag = interpolate(rgb_features, params.features_per_bag)

  File "E:\Codes\AnomalyDetection_CVPR18-master\utils\array_util.py", line 39, in interpolate
    interpolated_features[count,:]=temp_vect

ValueError: could not broadcast input array from shape (4096,) into shape (109,)

please help me fix it 
Thank you
