### ISSUE TITLE
C3D settings are different.

### ISSUE THREAD

**Issue by k173038** [ptirupat/AnomalyDetection_CVPR18#6]
Hi,

Thanks for your prompt reply on my previous comments. After reviewing your code, waqas's implementation and C3D's suggestions, I got stucked. Please, have a look on it and give me suggestion.

As per my understanding followings are settings that are mentioned in Waqas's paper,  applied prior to videos feature's extractions:
1). Divided video into 32 temporal segments and make it part of bag depending on its nature.
2). Fixed frame rate to 30 FPS and resized each frame size to 240x320 pixels.
3). Computed C3D features for every 16-frame clip followed by L2 normalization.
4). To obtain features of particular video segment (out of 32 segments = one training video), average of all 16-frame video clips (as mentioned in point.3) is considered.
5). After feature's extraction's they have 4096 features of 32 segments in one file.

 C3D suggestions:
1). 5 clips of 2 seconds each. (does it make any difference?)
2). Clips are resized to 128x171
3). 16x112x112 crops.

Your implementations:
0). Used sports Model weights (why we have selected the sports model weights are testing?)
1). Selected 16 evenly samples frames from each given input video (neither segment nor clip).
2). Resized video to 128x171.
3). Subtracted from c3d_mean. (What is reason to subtract the frame size from C3d-mean?)
4). Cropped the frames to 16x112x112.

Thanks once again for all queries that you have replied. It will be nicer if you share your email address to me for direct co-ordinations if required.

Regards,

Kanwal Kumar (K173038@nu.edu.pk)

**Comment by ptirupat** [comment]
I am following the feature extraction from C3D as suggested in their paper but not the process Waqas's paper uses. I did not compute the AUC metrics to compare the overall results but visually looking at some of the qualitative outputs, the performance seems similar.
