### ISSUE TITLE
IndexError: tuple index out of range

### ISSUE THREAD

**Issue by Shiny128** [ptirupat/AnomalyDetection_CVPR18#8]
Hello 
I have encountered the following error when i tried to run demo.py

Number of clips in the video :  0
Models initialized
Traceback (most recent call last):
  File "demo.py", line 53, in <module>
    run_demo()
  File "demo.py", line 38, in run_demo
    rgb_feature_bag = interpolate(rgb_features, params.features_per_bag)
  File "/home/dell/Documents/AnomalyDetection_CVPR18-master/utils/array_util.py", line 19, in interpolate
    feature_size = np.array(features).shape[1]
IndexError: tuple index out of range

Please help me fix it  

Thank you

**Comment by k173038** [comment]
Dear Shiny,

Kindly provide the valid video having certain clips to the model otherwise, it will through the error similar to that you got.

**Comment by Shiny128** [comment]
Hello
Thank You for your response, I have given input video from the same dataset and still encounterd this error
Please guide me to get the  output to different videos from the dataset
Thank you

**Comment by ptirupat** [comment]
Check the number of frames read from the video. It could an issue with OpenCV installation.

**Comment by Shiny128** [comment]
It says the number of clips in the video : 0
Is it an issue with openCV? 
If yes, how do I resolve it ?

**Comment by ptirupat** [comment]
Seems to be an issue with OpenCV. Check if you have ffmpeg installed.

**Comment by Shiny128** [comment]
Yes I have ffmpeg installed and still encounter the above error
